name: Annihilation
version: '${project.version}'
main: com.example.annihilationnexus.AnnihilationNexus
api-version: '1.21'
authors: ['Utr3cht']
description: A Nexus plugin for the Annihilation game mode.
commands:
  class:
    description: Select your class.
    usage: /class [class_name]
  team:
    description: Join a team.
    usage: /team <team_name>
  nexus:
    description: Admin commands for Nexus management.
    usage: /nexus [create|destroy|sethealth]
    permission: annihilation.admin
    permission-message: You do not have permission to use this command.
  anni:
    description: Admin commands for Annihilation.
    usage: /anni [start|stop|reload]
    default: op
  togglescoreboard:
    description: Toggle scoreboard visibility.
    usage: /togglescoreboard
  classregion:
    description: Manage class restricted regions.
    usage: /classregion [create|delete|list]
    permission: annihilation.admin
    permission-message: You do not have permission to use this command.
  chat:
    description: Manage chat translation settings
    usage: /chat <lang|on|off> [args]
  myxp:
    description: Check your current XP balance.
    usage: /myxp
  sbrank:
    description: Open GUI to change display rank prefix
    usage: /sbrank
  clan:
    description: Manage clans
    usage: /clan <create|invite|join|view|leave>
  rank:
    description: Shows your rank progress
    usage: /rank
  ranking:
    description: Shows the XP leaderboard
    usage: /ranking [page]

permissions:
  annihilation.admin:
    description: Allows access to Annihilation admin commands.
    default: op
