name: AnnihilationNexus
version: 1.0-SNAPSHOT
main: com.example.annihilationnexus.AnnihilationNexus
api-version: '1.21'
authors: [Gemini]
description: A Nexus plugin for the Annihilation game mode.
commands:
  class:
    description: Sets a player's class.
    usage: /<command> <player> <class>
    permission: annihilationnexus.class.set
  nexus:
    description: Nexus administration commands.
    usage: /<command> <subcommand>
    permission: annihilationnexus.admin
